arch:
  - amd64
language: minimal
sudo: required
packages:
  - jq
before_install:
  - curl -fsSL https://raw.githubusercontent.com/pschmitt/ci-setup-docker-buildx/master/setup.sh | bash
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - travis_retry ./build.sh
